import Head from "next/head";
import AIIndex from "./components/AI";
import Footer from "./components/home/footer";

export default function AI () {
    return (
      <><Head>
        <title>Artifical Intellegence</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <AIIndex/>
      <Footer/>
    </>
    );
  };